on:
push:
 branches: [main]
pull_request:
 branches: [main]

os: [linux]
dist: focal

language: node_js
node_js:
 - 'stable'
cache:
 directories:
  - 'node_modules'

script:
 - echo 'Starting Build'
 - echo 'Installing Dependencies'
 - npm install
 - echo 'Running Tests'
 - mocha

notifications:
 email:
  recipients:
   - dmreh@outlook.com
   - m.rehnert@safethishome.com
  on_success: change
  on_failure: always
