name: Travis_CI_esmtpm

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

language: node_js
node_js:
  - 12
os:
  - linux
dist: focal

before_install:
  - npm i -g npm@>=6.14.x

jobs:
  build:
    - run: npm ci
    - run: npm install
    - run: node server
    - run: npm ci

npm cache: false

notifications:
  email:
    recipients:
      - dmreh@outlook.com
      - m.rehnert@safethishome.com
    on_success: never # default: change
    on_failure: always # default: always
